### ISSUE TITLE
Ask about weight

### ISSUE THREAD

**Issue by ThanhPham1987** [yehengchen/Object-Detection-and-Tracking#22]
Hi yehengchen,
Can you share file 'model_data/market1501.pb'?
Best regards,
PeterPham

**Comment by yehengchen** [comment]
Hi,@ThanhPham1987  
You can download the market1501.pb  from [Google Driver](https://drive.google.com/file/d/1Qh6FiQ8mh-gSpLQbwAlMm9fOFkyWaEVy/view?usp=sharing)

**Comment by ThanhPham1987** [comment]
Hi Yehengchen,
Thank you very much!
Best regards,
PeterPham
