### ISSUE TITLE
deep_sort_yolov3/counter.txt, deep_sort_yolov3/num.txt and model_data/market1501.pb files are missing

### ISSUE THREAD

**Issue by Sadam1195** [yehengchen/Object-Detection-and-Tracking#23]
Hello @yehengchen, I am running `YOLOv3 + Deep_SORT` example, but I can't find the files required to run this example, how do I create them or can you provide them? That'd be great help. 

**deep_sort_yolov3/counter.txt
deep_sort_yolov3/num.txt
model_data/market1501.pb**

**Comment by yehengchen** [comment]
Hi, @Sadam1195 
The .txt file just for testing,  I will make some changes to main.py. Sorry about that.
About model_data/market1501.pb please consult  #22

**Comment by Sadam1195** [comment]
> Hi, @Sadam1195
> The .txt file just for testing, I will make some changes to main.py. Sorry about that.
> About model_data/market1501.pb please consult #22

Thanks for the quick reply, how do I test a tracking demo on a video?

**Comment by Sadam1195** [comment]
> > Hi, @Sadam1195
> > The .txt file just for testing, I will make some changes to main.py. Sorry about that.
> > About model_data/market1501.pb please consult #22
> 
> Thanks for the quick reply, how do I test a tracking demo on a video?

never mind, I tweaked your code a bit and voila.
