### ISSUE TITLE
代码在我的机子上这个问题能看下么

### ISSUE THREAD

**Issue by wf0934** [yehengchen/Object-Detection-and-Tracking#24]
运行时的错误提示：
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 43095 values, but the requested shape requires a multiple of 5577
         [[{{node Reshape_3}}]]
         [[concat_12/_2923]]
  (1) Invalid argument: Input to reshape is a tensor with 43095 values, but the requested shape requires a multiple of 5577
         [[{{node Reshape_3}}]]
之前以为是视频的问题，调成640*480依然没有解决
代码定位应该是在yolo.py中我这边116行  out_boxes,out _scores这行开始

**Comment by yehengchen** [comment]
@wf0934 `yolo.py` 里的几个文件路径改了吗？

**Comment by wf0934** [comment]
> @ wf0934 `yolo.py`里的几个文件路径改了吗？
self.model_path = 'model_data/yolo.h5'
self.anchors_path = 'model_data/yolo_anchors.txt'
self.classes_path = 'model_data/obj.txt'
这个文件路径没有问题吧

**Comment by yehengchen** [comment]
@wf0934 `obj.txt` 这个file里面的类别和权重应该对应不是，你换成coco的类别试一下

**Comment by wf0934** [comment]
哇，终于通了，调程序调了两天了。非常感谢！！！（顿首）什么时候能像大佬一样啊～～～
