### ISSUE TITLE
是否使用了gpu？？？

### ISSUE THREAD

**Issue by sunshuai95** [yehengchen/Object-Detection-and-Tracking#36]
师兄你好，YOLOv3 + SORT - Person Counter这个模型是否使用的gpu？
![image](https://user-images.githubusercontent.com/45874085/72416746-5b148800-37b2-11ea-85de-1f1fd39b6ed5.png)
如图，一小段视频用了699s，使用nVidia-smi查看，貌似没有使用gpu，
![image](https://user-images.githubusercontent.com/45874085/72416983-d5dda300-37b2-11ea-8b27-3197b14ac277.png)
如何使用gpu加速？？

**Comment by yehengchen** [comment]
@sunshuai95 这个SORT的代码目前是不支持GPU加速的，你可以review一下代码尝试改成GPU版本

**Comment by yehengchen** [comment]
> 师兄你好，YOLOv3 + SORT - Person Counter这个模型是否使用的gpu？
> ![image](https://user-images.githubusercontent.com/45874085/72416746-5b148800-37b2-11ea-85de-1f1fd39b6ed5.png)
> 如图，一小段视频用了699s，使用nVidia-smi查看，貌似没有使用gpu，
> ![image](https://user-images.githubusercontent.com/45874085/72416983-d5dda300-37b2-11ea-8b27-3197b14ac277.png)
> 如何使用gpu加速？？

**Comment by yehengchen** [comment]
@sunshuai95 这个SORT的代码目前是不支持GPU加速的，有时间可以review一下代码尝试改成GPU版本
