### ISSUE TITLE
你好，如果我想检测跟踪房子，那么yolo.weight是通过yolo训练得来的吗？

### ISSUE THREAD

**Issue by 201814476285951** [yehengchen/Object-Detection-and-Tracking#6]

**Comment by 201814476285951** [comment]
打错了，如果我想检测跟踪其他物体，那么yolo.weight是通过yolo训练得来的吗？

**Comment by yehengchen** [comment]
> 打错了，如果我想检测跟踪其他物体，那么yolo.weight是通过yolo训练得来的吗？
目标追踪的步骤： 目标检测 --> 对检测的目标进行相似度比对-->目标追踪
目标检测的话你只要训练 YOLO得到 yolo.weight 就够了，这里的目标追踪 DeepSORT 的weight是用人的Re-ID数据训练的，可以用在别的目标追踪但是效果不太好，建议训练自己需要的目标Re-ID weight 用来追踪其他目标。
训练目标追踪可以参考：https://github.com/nwojke/cosine_metric_learning

**Comment by yehengchen** [comment]
> 打错了，如果我想检测跟踪其他物体，那么yolo.weight是通过yolo训练得来的吗？

目标追踪的步骤： 目标检测 --> 对检测的目标进行相似度比对-->目标追踪
目标检测的话你只要训练 YOLO得到 yolo.weight 就够了，这里的目标追踪 DeepSORT 的weight是用人的Re-ID数据训练的，可以用在别的目标追踪但是效果不太好，建议训练自己需要的目标Re-ID weight 用来追踪其他目标。
训练目标追踪可以参考：https://github.com/nwojke/cosine_metric_learning
