### ISSUE TITLE
既然是opencv读到的图，为什么要用Image去预处理呢？

### ISSUE THREAD

**Issue by zhishao** [yehengchen/Object-Detection-and-Tracking#60]

**Comment by zhishao** [comment]
我的GPU是2070S，只能跑10FPS，请问还有哪里可以优化呢？记得原版v4能到50+吧？

**Comment by yehengchen** [comment]
@zhishao 
1. 这里使用的训练参数是 __width=608 height=608__ 加上跟踪算法跑出10+ FPS是正常的
2. 只考虑速度上的优化可以减小训练中 __width & height__ 参数以及缩小预测时 __input image size__

可以参考作者的对比实验：
FPS on RTX 2070 (R) and Tesla V100 (V):
width=608 height=608 in cfg: 65.7% mAP@0.5 (43.5% AP@0.5:0.95) - 34(R) FPS / 62(V) FPS - 128.5 BFlops
width=512 height=512 in cfg: 64.9% mAP@0.5 (43.0% AP@0.5:0.95) - 45(R) FPS / 83(V) FPS - 91.1 BFlops
width=416 height=416 in cfg: 62.8% mAP@0.5 (41.2% AP@0.5:0.95) - 55(R) FPS / 96(V) FPS - 60.1 BFlops
width=320 height=320 in cfg: 60% mAP@0.5 ( 38% AP@0.5:0.95) - 63(R) FPS / 123(V) FPS - 35.5 BFlops

**Comment by zhishao** [comment]
@yehengchen 好的，我改下输入试试，非常感谢！
