### ISSUE TITLE
InvalidArgumenError for Reshape

### ISSUE THREAD

**Issue by ntucschen** [yehengchen/Object-Detection-and-Tracking#9]
Hi,

I ran the code of deep_sort_yolov3 with instruction as `python3 main.py -c person -i data/cam1.avi`
I met the following error which seems to be caused by the shape mismatch.
Do you have any suggestion how to fix this?
And can you provide a testing video?
Thank you.

`InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 312375 values, but the requested shape requires a multiple of 40425
	 [[Node: Reshape_3 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2d_59/BiasAdd, Reshape_3/shape)]]`

**Comment by Guanwh** [comment]
@ntucschen 
Hi, I got the same error...Have you solved it?

**Comment by yehengchen** [comment]
This error was from a shape mismatch. 
Sorry, I have no idea for this error. 
Here is testing video in Google Driver [https://drive.google.com/open?id=14jo0UIfkCt2PdsjW4cC0tHM31TkiWbsf](url)

**Comment by yehengchen** [comment]
> As you said this error was from a shape mismatch.
> Here is testing video in Google Drive.
> [ [ TownCentreXVID.avi ]](https://drive.google.com/open?id=14jo0UIfkCt2PdsjW4cC0tHM31TkiWbsf)
