### ISSUE TITLE
图像分割

### ISSUE THREAD

**Issue by SWJTUJoeGit** [yehengchen/Object-Detection-and-Tracking#94]
我想请问下您之前利用mmsegmentation做图像分割做出来的结果有五类是nan，能告诉我您是怎么解决的吗？谢谢

**Comment by yehengchen** [comment]
> 我想请问下您之前利用mmsegmentation做图像分割做出来的结果有五类是nan，能告诉我您是怎么解决的吗？谢谢

我把标注文件的灰度值和label对应上就行了

**Comment by SWJTUJoeGit** [comment]
非常感谢您的解答！但是我不是很确定您是怎么对应的，是通过设置CLASSES和PALETTE的值吗？我使用的数据是灰度图，值只有0和255，分类只分以下两类。
   CLASSES = ('builing', 'BG')
   PALETTE = [[255, 255, 255], [0, 0, 0]]
但是训练结果building总是100%，BG总是nan，如果您有啥解决思路？麻烦您帮助我下，非常感谢

**Comment by yehengchen** [comment]
灰度图对应的两个类别灰度值是[0]和[1]吗？出现nan也有可能你把ignore&nbsp;index指向的BG




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yehengchen/Object-Detection-and-Tracking"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 下午4:15
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yehengchen/Object-Detection-and-Tracking] 图像分割 (#94)





 
非常感谢您的解答！但是我不是很确定您是怎么对应的，是通过设置CLASSES和PALETTE的值吗？我使用的数据是灰度图，值只有0和255，分类只分以下两类。
 CLASSES = ('builing', 'BG')
 PALETTE = [[255, 255, 255], [0, 0, 0]]
 但是训练结果building总是100%，BG总是nan，如果您有啥解决思路？麻烦您帮助我下，非常感谢

**Comment by KunalChaturvedi28** [comment]
Hi @yehengchen, 
I changed the masks to grayscale but could not understand what is meant by "I changed the Grayscale value of each category to 0,1,2..."
I have been stuck at this part for a week. Could you please let me know what did you mean by this?

Regards,
Kunal

![image](https://user-images.githubusercontent.com/47566894/112468514-5a9c5780-8d8e-11eb-954b-ba3e7eb286ae.png)
"

**Comment by SWJTUJoeGit** [comment]
非常感谢，我已经顺利解决了这个问题！感谢您的及时回复

**Comment by SWJTUJoeGit** [comment]
> 灰度图对应的两个类别灰度值是[0]和[1]吗？出现nan也有可能你把ignore&nbsp;index指向的BG
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yehengchen/Object-Detection-and-Tracking" ***@***.***&gt;; 发送时间:&nbsp;2021年3月25日(星期四) 下午4:15 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [yehengchen/Object-Detection-and-Tracking] 图像分割 (#94) 非常感谢您的解答！但是我不是很确定您是怎么对应的，是通过设置CLASSES和PALETTE的值吗？我使用的数据是灰度图，值只有0和255，分类只分以下两类。 CLASSES = ('builing', 'BG') PALETTE = [[255, 255, 255], [0, 0, 0]] 但是训练结果building总是100%，BG总是nan，如果您有啥解决思路？麻烦您帮助我下，非常感谢 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

非常感谢，我已经顺利解决了这个问题！感谢您的及时回复

**Comment by rouchoo** [comment]
请教一下，您是如何解决的？我的训练图片是单通道的灰度图，也是一直出现nan。谢谢您！
